'use client';
import { useMemo, useState, useTransition } from 'react';
import { recordClosingStockAction } from '@/app/(dashboard)/chef/closing-stock/actions';
type Item = { id: number; name: string; category_name: string; default_qty?: number };
export function ClosingStockWorkflow({ items, defaultDate }: { items: Item[]; defaultDate: string }) {
  const [entryDate, setEntryDate] = useState(defaultDate); const [note, setNote] = useState(''); const [values, setValues] = useState<Record<number, string>>(() => Object.fromEntries(items.map((i) => [i.id, i.default_qty === undefined ? '' : String(i.default_qty)]))); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null); const [isPending, startTransition] = useTransition();
  const rows = useMemo(() => items.map((item) => ({ ...item, qty: Number(values[item.id] || '0') })), [items, values]);
  const saveBulk = () => { setError(null); setSuccess(null); const changed = rows.filter((row) => !Number.isNaN(row.qty) && row.qty >= 0); if (!changed.length) return setError('Enter at least one quantity.'); startTransition(async () => { const result = await recordClosingStockAction({ entry_date: entryDate, note: note || undefined, items: changed.map((row) => ({ menu_item_id: row.id, qty: row.qty })) }); if (!result.ok) return setError(result.error ?? 'Request failed.'); setSuccess('Closing stock saved. It will be used as tomorrow’s opening default when no explicit opening stock exists.'); }); };
  return <section className="panel"><h2 className="section-title">Closing stock entry</h2><p className="section-subtitle">Record end-of-day actual stock for stock-tracked items.</p><div className="form-grid" style={{ marginTop: 12 }}><div className="form-col-4"><input type="date" value={entryDate} onChange={(e) => setEntryDate(e.target.value)} className="input" /></div><div className="form-col-8"><input value={note} onChange={(e) => setNote(e.target.value)} placeholder="Closing note" className="input" /></div></div><div className="table-shell" style={{ marginTop: 12 }}><table className="table"><thead><tr><th>Item</th><th>Category</th><th className="money">Actual closing qty</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.name}</td><td>{row.category_name}</td><td className="money"><input value={values[row.id] ?? ''} onChange={(e) => setValues((prev) => ({ ...prev, [row.id]: e.target.value }))} className="input" style={{ width: 110, marginLeft: 'auto' }} inputMode="decimal" /></td></tr>)}</tbody></table></div>{error ? <p className="alert alert-error" style={{ marginTop: 10 }}>{error}</p> : null}{success ? <p className="alert alert-success" style={{ marginTop: 10 }}>{success}</p> : null}<button type="button" onClick={saveBulk} disabled={isPending} className="btn btn-primary" style={{ marginTop: 10 }}>{isPending ? 'Saving...' : 'Save closing stock'}</button></section>;
}
