import { DashboardShell } from '@/components/dashboard/dashboard-shell';
import { MetricCard, EmptyState } from '@/components/ui/fryva-ui';
import { requireRole } from '@/lib/auth/guards';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import { kenyaDayUtcRange, kenyaTodayDate } from '@/lib/time/kenya';
function money(v: number) { return new Intl.NumberFormat('en-KE', { style: 'currency', currency: 'KES' }).format(v); }
export default async function Page({ searchParams }: { searchParams: Promise<{ from?: string; to?: string }> }) {
  await requireRole(['owner']); const params = await searchParams; const today = kenyaTodayDate(); const from = params.from ?? today; const to = params.to ?? today; const supabase = await createServerSupabaseClient(); const todayRange = kenyaDayUtcRange(today);
  const [{ data: meals }, { data: todayMeals }] = await Promise.all([
    supabase.from('staff_meal_records').select('id, staff_name, staff_option, note, business_date, total_value, recorded_at, sale_id, sales(sale_items(menu_item_name, quantity, line_total))').gte('business_date', from).lte('business_date', to).order('business_date', { ascending: false }),
    supabase.from('staff_meal_records').select('staff_name,total_value').gte('recorded_at', todayRange.from).lt('recorded_at', todayRange.to),
  ]);
  const todayTotal = (todayMeals ?? []).reduce((s, r) => s + Number(r.total_value), 0); const rangeTotal = (meals ?? []).reduce((s, r) => s + Number(r.total_value), 0);
  const byStaff = new Map<string, number>(); const items = new Map<string, { qty: number; value: number }>();
  for (const meal of meals ?? []) { byStaff.set(meal.staff_name, (byStaff.get(meal.staff_name) ?? 0) + Number(meal.total_value)); for (const item of ((meal.sales as any)?.sale_items ?? [])) { const key = `${meal.staff_name} ate ${item.menu_item_name}`; const prev = items.get(key) ?? { qty: 0, value: 0 }; items.set(key, { qty: prev.qty + Number(item.quantity), value: prev.value + Number(item.line_total) }); } }
  return <DashboardShell role="owner" title="Staff Meals" description="Owner-only tracking of staff consumption value separate from revenue."><section className="kpi-grid"><MetricCard label="Today staff meal value" value={money(todayTotal)} /><MetricCard label="Selected range value" value={money(rangeTotal)} /><MetricCard label="Staff with meals" value={String(byStaff.size)} /></section><section className="panel"><form className="filter-bar"><input type="date" name="from" defaultValue={from} className="input" /><input type="date" name="to" defaultValue={to} className="input" /><button className="btn btn-primary">Filter</button></form></section><section className="panel"><h2 className="section-title">Value per staff</h2>{byStaff.size === 0 ? <EmptyState title="No staff meals" description="No staff meals recorded in this range." /> : <div className="table-shell"><table className="table"><thead><tr><th>Staff</th><th className="money">Total value</th></tr></thead><tbody>{Array.from(byStaff.entries()).map(([staff, total]) => <tr key={staff}><td>{staff}</td><td className="money">{money(total)}</td></tr>)}</tbody></table></div>}</section><section className="panel"><h2 className="section-title">Item-level breakdown</h2><div className="list-stack">{Array.from(items.entries()).map(([label, row]) => <article key={label} className="row-card"><strong>{label}</strong><p className="section-subtitle">Qty {row.qty} · value {money(row.value)}</p></article>)}</div></section><section className="panel"><h2 className="section-title">Detailed staff meal history</h2>{(meals ?? []).length === 0 ? <EmptyState title="No records" description="Staff meal records will appear here." /> : <div className="list-stack">{(meals ?? []).map((meal: any) => <article key={meal.id} className="row-card"><strong>{meal.staff_name}</strong><p className="section-subtitle">{meal.business_date} · {money(Number(meal.total_value))}{meal.note ? ` · ${meal.note}` : ''}</p><ul>{(meal.sales?.sale_items ?? []).map((item: any) => <li key={`${meal.id}-${item.menu_item_name}`}>{item.quantity} {item.menu_item_name} — {money(Number(item.line_total))}</li>)}</ul></article>)}</div>}</section></DashboardShell>;
}
