import { DashboardShell } from '@/components/dashboard/dashboard-shell';
import { MetricCard, EmptyState } from '@/components/ui/fryva-ui';
import { StockAlertsReviewForm } from '@/components/owner/stock-alerts-review-form';
import { requireRole } from '@/lib/auth/guards';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import { kenyaDayUtcRange, kenyaTodayDate } from '@/lib/time/kenya';
function money(v: number) { return new Intl.NumberFormat('en-KE', { style: 'currency', currency: 'KES' }).format(v); }
export default async function Page({ searchParams }: { searchParams: Promise<{ date?: string; status?: string }> }) {
  await requireRole(['owner']); const params = await searchParams; const date = params.date ?? kenyaTodayDate(); const supabase = await createServerSupabaseClient(); const range = kenyaDayUtcRange(date);
  const [{data: items},{data: opening},{data: prod},{data: closing},{data: sales},{data: staff},{data: purchases},{data: reviews}] = await Promise.all([
    supabase.from('menu_items').select('id,name,selling_price').eq('active', true).eq('stock_tracked', true),
    supabase.from('opening_stock_entries').select('menu_item_id,qty').eq('entry_date', date),
    supabase.from('stock_production_entries').select('menu_item_id,qty').eq('entry_date', date),
    supabase.from('closing_stock_entries').select('menu_item_id,qty,entered_by,profiles!closing_stock_entries_entered_by_fkey(full_name)').eq('entry_date', date),
    supabase.from('sale_items').select('menu_item_id,quantity,sales!inner(sold_at,status,payment_method,sold_by)').gte('sales.sold_at', range.from).lt('sales.sold_at', range.to).eq('sales.status', 'finalized'),
    supabase.from('sale_items').select('menu_item_id,quantity,sales!inner(sold_at,status,payment_method)').gte('sales.sold_at', range.from).lt('sales.sold_at', range.to).eq('sales.status', 'finalized').eq('sales.payment_method', 'staff'),
    supabase.from('purchases').select('menu_item_id,item_name,qty').eq('purchase_date', date),
    supabase.from('stock_variance_reviews').select('menu_item_id,status,review_note,reviewed_at').eq('business_date', date),
  ]);
  const sellerIds = Array.from(new Set((sales ?? []).map((row: any) => row.sales?.sold_by).filter(Boolean)));
  const { data: profiles } = sellerIds.length ? await supabase.from('profiles').select('id, full_name').in('id', sellerIds) : { data: [] as Array<{ id: string; full_name: string }> };
  const profileMap = new Map((profiles ?? []).map((profile) => [profile.id, profile.full_name]));
  const sum = (rows:any[]|null|undefined, field='qty') => { const m=new Map<number,number>(); for (const r of rows??[]) if (r.menu_item_id) m.set(r.menu_item_id,(m.get(r.menu_item_id)??0)+Number(r[field])); return m; };
  const openingM=sum(opening), prodM=sum(prod), closeM=sum(closing), staffM=sum(staff,'quantity'), purchM=sum(purchases); const soldM=new Map<number,number>(); const staffNames=new Map<number,Set<string>>();
  for (const row of sales??[]) { if ((row as any).sales?.payment_method !== 'staff') soldM.set(row.menu_item_id,(soldM.get(row.menu_item_id)??0)+Number(row.quantity)); const s=staffNames.get(row.menu_item_id)??new Set<string>(); s.add(profileMap.get((row as any).sales?.sold_by) ?? 'Unknown'); staffNames.set(row.menu_item_id,s); }
  const reviewM=new Map((reviews??[]).map((r:any)=>[r.menu_item_id,r]));
  const rows=(items??[]).map((item:any)=>{ const opening=openingM.get(item.id)??0, produced=prodM.get(item.id)??0, purchased=purchM.get(item.id)??0, sold=soldM.get(item.id)??0, staffMeals=staffM.get(item.id)??0, expected=opening+produced+purchased-sold-staffMeals, actual=closeM.get(item.id); const variance=actual===undefined?null:actual-expected; const severity=variance===null||variance===0?'Minor':Math.abs(variance)>=10?'Critical':Math.abs(variance)>=3?'Warning':'Minor'; return { item, opening, produced, purchased, sold, staffMeals, expected, actual, variance, severity, review:reviewM.get(item.id), staff:Array.from(staffNames.get(item.id)??[]) }; }).filter(r=>r.actual!==undefined && r.variance!==0);
  const filtered=params.status==='resolved'?rows.filter(r=>r.review?.status==='resolved'):rows.filter(r=>r.review?.status!=='resolved');
  return <DashboardShell role="owner" title="Stock Alerts" description="Unexplained stock variance review. This does not accuse staff; it highlights records needing review."><section className="kpi-grid"><MetricCard label="Unresolved alerts" value={String(rows.filter(r=>r.review?.status!=='resolved').length)} /><MetricCard label="Resolved alerts" value={String(rows.filter(r=>r.review?.status==='resolved').length)} /><MetricCard label="Date" value={date} /></section><section className="panel"><form className="filter-bar"><input type="date" name="date" defaultValue={date} className="input" /><select name="status" defaultValue={params.status ?? 'unresolved'} className="select"><option value="unresolved">Unresolved</option><option value="resolved">Resolved</option></select><button className="btn btn-primary">Filter</button></form></section><section className="panel"><h2 className="section-title">Variance alerts needing careful review</h2><p className="section-subtitle">Expected closing = opening + production + linked purchases − sold − staff meals. Check sales and kitchen records.</p>{filtered.length===0?<EmptyState title="No stock alerts" description="No matching variances for this date."/>:<div className="table-shell" style={{marginTop:12}}><table className="table"><thead><tr><th>Item</th><th>Severity</th><th className="money">Opening</th><th className="money">Produced</th><th className="money">Purchased</th><th className="money">Sold</th><th className="money">Staff meals</th><th className="money">Expected</th><th className="money">Actual</th><th className="money">Variance</th><th>Review</th></tr></thead><tbody>{filtered.map(r=><tr key={r.item.id}><td><strong>{r.item.name}</strong><p className="section-subtitle">Staff on shift: {r.staff.join(', ') || 'None found'} · Est. value {money(Math.abs(r.variance ?? 0)*Number(r.item.selling_price ?? 0))}</p></td><td><span className={`status-chip ${r.severity==='Critical'?'status-unpaid':r.severity==='Warning'?'status-warning':'status-info'}`}>{r.severity}</span></td><td className="money">{r.opening}</td><td className="money">{r.produced}</td><td className="money">{r.purchased}</td><td className="money">{r.sold}</td><td className="money">{r.staffMeals}</td><td className="money">{r.expected}</td><td className="money">{r.actual}</td><td className="money">{r.variance}</td><td>{r.review?.status==='resolved'?<span>Resolved · {r.review.review_note}</span>:<StockAlertsReviewForm date={date} itemId={r.item.id}/>}</td></tr>)}</tbody></table></div>}</section></DashboardShell>;
}
